import BlogShell from "@/components/BlogShell";
import { Button } from "@/components/ui/button";
import { countStudentTools, getStudentSpecialty, studentSpecialties, type StudentSpecialty } from "@/lib/studentDirectory";
import { ArrowLeft, BookOpenCheck, BrainCircuit, CheckCircle2, ExternalLink, FlaskConical, GraduationCap, Laptop, Lightbulb, Palette, ShieldCheck, Sparkles } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

const icons = { science: FlaskConical, humanities: BookOpenCheck, computing: Laptop, business: Palette };
const accentClasses = { violet: "border-violet-300/20 bg-violet-400/[0.055] text-violet-100", cyan: "border-cyan-300/20 bg-cyan-300/[0.055] text-cyan-100", amber: "border-amber-300/20 bg-amber-300/[0.055] text-amber-100", emerald: "border-emerald-300/20 bg-emerald-300/[0.055] text-emerald-100" };

export default function StudentDirectoryPage() {
  const [specialtyId, setSpecialtyId] = useState<StudentSpecialty["id"]>("science");
  const specialty = getStudentSpecialty(specialtyId);
  const SpecialtyIcon = icons[specialty.id];
  return <BlogShell>
    <section className="relative isolate overflow-hidden border-b border-white/8"><div className="pointer-events-none absolute inset-0 -z-10 bg-[radial-gradient(circle_at_12%_18%,rgba(139,92,246,.28),transparent_29%),radial-gradient(circle_at_82%_28%,rgba(34,211,238,.18),transparent_26%),linear-gradient(120deg,#070919,#0e1834_55%,#071021)]" /><div className="container grid gap-9 py-14 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><p className="inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/[0.08] px-3 py-1.5 text-xs font-bold text-cyan-100"><GraduationCap className="h-3.5 w-3.5" />دليل مجاني للطلاب</p><h1 className="mt-5 max-w-3xl font-display text-4xl font-black leading-[1.14] text-white md:text-6xl">دليل الطلاب: <span className="text-gradient">أدوات حسب تخصصك</span></h1><p className="mt-5 max-w-2xl text-base leading-8 text-slate-300 md:text-lg">لا تبدأ من قائمة طويلة عشوائية. اختر تخصصك، اعرف لماذا قد تفيدك الأداة، ثم افتحها مباشرة وراجع الناتج بنفسك.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild className="bg-violet-500 px-6 hover:bg-violet-400"><a href="#specialties">اختر تخصصك <ArrowLeft className="mr-2 h-4 w-4" /></a></Button><Button asChild variant="outline" className="border-white/15 bg-white/[0.03] text-slate-100 hover:bg-white/10 hover:text-white"><Link href="/student">افتح مساحة الطالب</Link></Button></div></div><div className="rounded-[2rem] border border-white/12 bg-[#090d22]/80 p-6 shadow-[0_24px_70px_rgba(0,0,0,.32)]"><div className="flex items-center justify-between"><p className="flex items-center gap-2 text-sm font-bold text-white"><Sparkles className="h-4 w-4 text-cyan-300" />ابدأ من الاحتياج</p><span className="rounded-full bg-violet-400/12 px-2.5 py-1 text-[10px] font-black text-violet-100">{countStudentTools()} أدوات</span></div><div className="mt-5 grid gap-3"><div className="rounded-2xl border border-violet-300/20 bg-violet-400/[0.07] p-4"><p className="text-xs font-bold text-violet-100">01 — اختر تخصصك</p><p className="mt-1 text-sm leading-6 text-slate-300">ابحث عن الأداة التي تخدم واجبك الحقيقي.</p></div><div className="rounded-2xl border border-cyan-300/20 bg-cyan-300/[0.06] p-4"><p className="text-xs font-bold text-cyan-100">02 — افتح أداة واحدة</p><p className="mt-1 text-sm leading-6 text-slate-300">جرّبها على مثال صغير قبل أن تعتمدها.</p></div><div className="rounded-2xl border border-emerald-300/20 bg-emerald-300/[0.06] p-4"><p className="text-xs font-bold text-emerald-100">03 — تحقق وحرّر</p><p className="mt-1 text-sm leading-6 text-slate-300">المصدر والفهم الشخصي أهم من الناتج السريع.</p></div></div></div></div></section>

    <section id="specialties" className="container py-12"><div className="mb-8 flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-bold text-cyan-300">أربعة مسارات واضحة</p><h2 className="mt-2 font-display text-3xl font-black text-white">اختر تخصصك ثم افتح أدواته</h2></div><p className="max-w-xl text-sm leading-7 text-slate-400">جميع الأزرار تقود إلى المواقع الرسمية للأدوات. توفر الخطة المجانية أو شروط الاستخدام قد تتغير، فراجعها قبل البدء.</p></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{studentSpecialties.map(item => { const Icon = icons[item.id]; const selected = specialtyId === item.id; return <button type="button" key={item.id} onClick={() => setSpecialtyId(item.id)} aria-pressed={selected} className={`rounded-[1.5rem] border p-5 text-right transition duration-200 ${selected ? "border-white/25 bg-white/[0.08] shadow-[0_15px_40px_rgba(0,0,0,.2)]" : "border-white/10 bg-white/[0.025] hover:-translate-y-1 hover:border-white/20"}`}><span className={`grid h-11 w-11 place-items-center rounded-2xl ${selected ? "bg-violet-400/20 text-violet-100" : "bg-white/[0.06] text-slate-300"}`}><Icon className="h-5 w-5" /></span><strong className="mt-5 block font-display text-xl text-white">{item.shortTitle}</strong><span className="mt-2 block text-sm leading-6 text-slate-400">{item.focus.join(" · ")}</span><span className="mt-4 inline-flex text-xs font-bold text-cyan-200">{selected ? "المسار المفتوح الآن" : "افتح المسار"}</span></button>})}</div>
      <div className="mt-6 overflow-hidden rounded-[2rem] border border-white/10 bg-[#0a0e23] shadow-[0_18px_55px_rgba(0,0,0,.22)]"><div className="grid gap-0 lg:grid-cols-[.72fr_1.28fr]"><aside className="border-b border-white/8 bg-[radial-gradient(circle_at_80%_12%,rgba(34,211,238,.14),transparent_26%),#0c112a] p-7 lg:border-b-0 lg:border-l"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-cyan-300/10 text-cyan-100"><SpecialtyIcon className="h-6 w-6" /></span><p className="mt-5 text-sm font-bold text-cyan-200">مسار {specialty.title}</p><h3 className="mt-2 font-display text-3xl font-black text-white">أدوات تخدم دراستك، لا تحل محلك</h3><p className="mt-4 text-sm leading-8 text-slate-300">{specialty.description}</p><div className="mt-6 rounded-2xl border border-amber-300/15 bg-amber-300/[0.055] p-4"><p className="flex items-center gap-2 text-xs font-bold text-amber-100"><ShieldCheck className="h-4 w-4" />قاعدة الاستخدام المسؤول</p><p className="mt-2 text-xs leading-6 text-slate-300">افهم المصدر أولاً، لا تضع بيانات حساسة، ولا تسلّم مخرجات الأداة كما هي في واجب أو اختبار.</p></div></aside><div className="p-6 md:p-8"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-slate-400">{specialty.tools.length} أدوات منتقاة</p><h3 className="mt-1 font-display text-2xl font-black text-white">ابدأ بأداة واحدة فقط</h3></div><BrainCircuit className="h-6 w-6 text-violet-200" /></div><div className="mt-6 grid gap-4">{specialty.tools.map((tool, index) => <article key={tool.name} className={`rounded-2xl border p-5 ${accentClasses[tool.accent]}`}><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><span className="text-[11px] font-black opacity-80">أداة 0{index + 1}</span><h4 className="mt-2 font-display text-xl font-black text-white">{tool.name}</h4><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-200">{tool.useCase}</p><p className="mt-3 flex items-start gap-1.5 text-xs leading-6 text-slate-300"><CheckCircle2 className="mt-0.5 h-3.5 w-3.5 shrink-0" />{tool.note}</p></div><a href={tool.url} target="_blank" rel="noopener noreferrer" className="inline-flex shrink-0 items-center justify-center gap-1.5 rounded-xl border border-white/15 bg-black/15 px-4 py-2.5 text-sm font-bold text-white transition hover:bg-white/10">افتح الأداة <ExternalLink className="h-3.5 w-3.5" /></a></div></article>)}</div></div></div></div>
    </section>
    <section className="container pb-16"><div className="grid gap-4 md:grid-cols-3"><Link href="/student" className="rounded-[1.7rem] border border-violet-300/20 bg-violet-400/[0.06] p-6 transition hover:-translate-y-1 hover:bg-violet-400/[0.1]"><Lightbulb className="h-5 w-5 text-violet-100" /><h3 className="mt-4 font-display text-xl font-black text-white">مساحة الطالب</h3><p className="mt-2 text-sm leading-7 text-slate-300">حوّل الموضوع إلى خطة وأسئلة وبطاقات داخل الموقع.</p></Link><Link href="/learning-plan" className="rounded-[1.7rem] border border-cyan-300/20 bg-cyan-300/[0.05] p-6 transition hover:-translate-y-1 hover:bg-cyan-300/[0.09]"><BookOpenCheck className="h-5 w-5 text-cyan-100" /><h3 className="mt-4 font-display text-xl font-black text-white">خطة 7 أيام</h3><p className="mt-2 text-sm leading-7 text-slate-300">تعلّم أساسيات الاستخدام المسؤول بخطوات يومية عملية.</p></Link><Link href="/tools" className="rounded-[1.7rem] border border-emerald-300/20 bg-emerald-300/[0.05] p-6 transition hover:-translate-y-1 hover:bg-emerald-300/[0.09]"><Sparkles className="h-5 w-5 text-emerald-100" /><h3 className="mt-4 font-display text-xl font-black text-white">دليل الأدوات الكامل</h3><p className="mt-2 text-sm leading-7 text-slate-300">قارن الخيارات حسب المهمة والتسعير ودعم العربية.</p></Link></div></section>
  </BlogShell>;
}
