import DashboardLayout from "@/components/DashboardLayout";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Lightbulb, ShieldAlert } from "lucide-react";

const labels = { tool: "أداة", comparison: "مقارنة", article: "مقال", other: "أخرى", pending: "بانتظار المراجعة", reviewed: "تمت المراجعة", implemented: "تم التنفيذ" };

function Content() { const { user, loading } = useAuth(); const isAdmin = user?.role === "admin"; const utils = trpc.useUtils(); const { data: suggestions, isLoading } = trpc.engagement.adminSuggestions.useQuery(undefined, { enabled: isAdmin }); const update = trpc.engagement.updateSuggestionStatus.useMutation({ onSuccess: () => utils.engagement.adminSuggestions.invalidate() }); if (loading) return <div className="p-10 text-slate-400">جارٍ التحقق…</div>; if (!isAdmin) return <div className="mx-auto max-w-xl rounded-3xl border border-rose-400/20 bg-rose-400/5 p-8 text-center"><ShieldAlert className="mx-auto h-9 w-9 text-rose-300" /><h1 className="mt-4 font-display text-2xl font-bold text-white">هذه الصفحة للمشرف فقط</h1></div>; return <div className="mx-auto max-w-5xl" dir="rtl"><p className="text-sm font-bold text-cyan-300">مشاركة الزوار</p><h1 className="mt-2 font-display text-3xl font-black text-white">الاقتراحات</h1><section className="mt-7 overflow-hidden rounded-3xl border border-white/10 bg-white/[0.035]">{isLoading ? <div className="p-8 text-slate-400">جارٍ التحميل…</div> : suggestions?.length ? suggestions.map(suggestion => <div key={suggestion.id} className="border-b border-white/8 px-6 py-5 last:border-0"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex gap-2"><span className="rounded-full bg-cyan-400/10 px-2.5 py-1 text-xs font-bold text-cyan-200">{labels[suggestion.category]}</span><span className="rounded-full bg-white/5 px-2.5 py-1 text-xs text-slate-400">{labels[suggestion.status]}</span></div><h2 className="mt-3 font-bold text-white">{suggestion.title}</h2><p className="mt-2 max-w-3xl text-sm leading-7 text-slate-400">{suggestion.details}</p></div><select value={suggestion.status} onChange={event => update.mutate({ id: suggestion.id, status: event.target.value as "pending" | "reviewed" | "implemented" })} className="h-9 rounded-lg border border-white/10 bg-[#080b1c] px-2 text-xs text-white"><option value="pending">بانتظار المراجعة</option><option value="reviewed">تمت المراجعة</option><option value="implemented">تم التنفيذ</option></select></div></div>) : <div className="p-12 text-center"><Lightbulb className="mx-auto h-8 w-8 text-cyan-300" /><p className="mt-3 text-slate-400">لا توجد اقتراحات بعد.</p></div>}</section></div>; }
export default function SuggestionsAdminPage() { return <DashboardLayout><Content /></DashboardLayout>; }
