import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Lightbulb, Send } from "lucide-react";
import { FormEvent, useState } from "react";

export default function SuggestionForm({ compact = false }: { compact?: boolean }) {
  const [title, setTitle] = useState(""); const [details, setDetails] = useState(""); const [category, setCategory] = useState<"tool" | "comparison" | "article" | "other">("tool"); const [message, setMessage] = useState("");
  const submit = trpc.engagement.submitSuggestion.useMutation({ onSuccess: () => { setTitle(""); setDetails(""); setCategory("tool"); setMessage("شكراً، وصل اقتراحك إلى قائمة المراجعة."); }, onError: () => setMessage("تعذر إرسال الاقتراح الآن. حاول مرة أخرى.") });
  function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage(""); submit.mutate({ title, details, category }); }
  return <section className={compact ? "" : "rounded-[2rem] border border-cyan-300/15 bg-gradient-to-l from-cyan-400/10 via-[#101429] to-[#090c1c] p-7 md:p-10"}><div className="max-w-2xl"><span className="inline-flex items-center gap-2 text-xs font-bold text-cyan-200"><Lightbulb className="h-4 w-4" />شارك في تطوير الدليل</span><h2 className="mt-3 font-display text-2xl font-black text-white">ما الأداة أو المقارنة التي تريدها؟</h2><p className="mt-2 text-sm leading-7 text-slate-300">أرسل اقتراحك، وسيراجعه فريق AIToolBox قبل إضافته إلى خطة المحتوى.</p><form onSubmit={handleSubmit} className="mt-6 grid gap-3"><div className="grid gap-3 sm:grid-cols-[1fr_180px]"><Input required value={title} onChange={event => setTitle(event.target.value)} className="h-11 border-white/10 bg-[#080c1c] text-white" placeholder="مثال: مقارنة بين Claude وGemini" /><select value={category} onChange={event => setCategory(event.target.value as typeof category)} className="h-11 rounded-xl border border-white/10 bg-[#080c1c] px-3 text-sm text-white"><option value="tool">أداة</option><option value="comparison">مقارنة</option><option value="article">مقال</option><option value="other">فكرة أخرى</option></select></div>{!compact && <Textarea required value={details} onChange={event => setDetails(event.target.value)} className="min-h-28 border-white/10 bg-[#080c1c] text-white" placeholder="اكتب ما تريد معرفته ولماذا يفيدك…" />}{compact && <Input required value={details} onChange={event => setDetails(event.target.value)} className="h-11 border-white/10 bg-[#080c1c] text-white" placeholder="سبب الاقتراح أو التفاصيل" />}<Button disabled={submit.isPending} className="w-fit bg-cyan-500 px-5 text-slate-950 hover:bg-cyan-300"><Send className="ml-2 h-4 w-4" />{submit.isPending ? "جارٍ الإرسال…" : "إرسال الاقتراح"}</Button></form>{message && <p role="status" className="mt-3 text-sm text-cyan-100">{message}</p>}</div></section>;
}
